django_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('phonebook/', include('phonebook.urls', namespace='phonebook')),
    path('admin/', admin.site.urls),
]

phonebook/urls.py
from django.urls import path

from . import views

app_name = 'phonebook'

urlpatterns = [
    path('', views.PersonList.as_view(), name='person_list'),
    path('new', views.PersonCreate.as_view(), name='person_new'),
    path('edit/<int:pk>', views.PersonUpdate.as_view(), name='person_edit'),
    path('delete/<int:pk>', views.PersonDelete.as_view(), name='person_delete'),
    path('new_email/<int:person_id>',
         views.EmailCreate.as_view(), name='email_new'),
    path('new_phone_number/<int:person_id>',
         views.PhoneNumberCreate.as_view(), name='phone_number_new')
]

phonebook/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)


class PhoneNumber(models.Model):
    person = models.ForeignKey(
        Person, editable=False, on_delete=models.CASCADE, related_name='phonenumbers')
    phone_number = models.CharField(max_length=50)


class Email(models.Model):
    person = models.ForeignKey(
        Person, editable=False, on_delete=models.CASCADE, related_name='emails')
    email = models.EmailField()

phonebook/forms.py
from django import forms
from .models import Email, PhoneNumber


class EmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            self.fields["person_id"] = forms.CharField(
                widget=forms.HiddenInput())
            super(EmailForm, self).__init__(self, *args, **kwargs)


class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            self.fields["person_id"] = forms.CharField(
                widget=forms.HiddenInput())
            super(PhoneNumberForm, self).__init__(self, *args, **kwargs)

phonebook/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.forms import ModelForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

from .forms import EmailForm, PhoneNumberForm
from phonebook.models import Person, Email, PhoneNumber
# Create your views here.


def index(request):
    return HttpResponse('This is a phone book app.')


class PersonList(ListView):
    model = Person
    template_name = '\phonebook\person_list.html'

    def get_context_data(self, **kwargs):
        context = super(PersonList, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = Person.objects.filter(
                Q(surname__icontains=query) | Q(name__icontains=query) |
                Q(emails__email__icontains=query) |
                Q(phonenumbers__phone_number__icontains=query)
            ).distinct()
        else:
            object_list = Person.objects.all()

        return object_list


class PersonCreate(CreateView):
    model = Person
    fields = ['name', 'surname']
    success_url = reverse_lazy('phonebook:person_list')


class PersonUpdate(UpdateView):
    model = Person
    fields = ['name', 'surname']
    success_url = reverse_lazy('phonebook:person_list')


class PersonDelete(DeleteView):
    model = Person
    success_url = reverse_lazy('phonebook:person_list')


class EmailCreate(CreateView):
    template_name = 'phonebook/email_form.html'
    form_class = EmailForm

    def form_valid(self, form):
        email = form.save(commit=False)
        person_id = form.data['person_id']
        person = get_object_or_404(Person, id=person_id)
        email.person = person
        return super(EmailCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        print(kwargs)
        context = super(EmailCreate, self).get_context_data(**kwargs)
        context['a_id'] = self.kwargs['person_id']
        return context

    success_url = reverse_lazy('phonebook:person_list')


class PhoneNumberCreate(CreateView):
    template_name = 'phonebook/phonenumber_form.html'
    form_class = PhoneNumberForm

    def form_valid(self, form):
        phone_number = form.save(commit=False)
        person_id = form.data['person_id']
        person = get_object_or_404(Person, id=person_id)
        phone_number.person = person
        return super(PhoneNumberCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        print(kwargs)
        context = super(PhoneNumberCreate, self).get_context_data(**kwargs)
        context['a_id'] = self.kwargs['person_id']
        return context

    success_url = reverse_lazy('phonebook:person_list')

phonebook/templates/phonebook/email_form.html
<h1><a href="{% url 'phonebook:person_list' %}"> phonebook </a></h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type=hidden name="person_id" value="{{ a_id }}">
    <input type="submit" value="Submit"/>
</form>

phonebook/templates/phonebook/person_confirm_delete.html
<h1><a href="{% url 'phonebook:person_list' %}"> phonebook </a></h1>

<form method="post">{% csrf_token %}
    Are you sure to delete "{{ object.name }} {{ object.surname }}" ? <br>
    <input type="submit" value="Delete" />
</form>

phonebook/templates/phonebook/person_form.html
<h1><a href="{% url 'phonebook:person_list' %}"> phonebook </a></h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
</form>

phonebook/templates/phonebook/person_list.html
<h1><a href="{% url 'phonebook:person_list' %}"> phonebook </a></h1>


<form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
    <button id="searchsubmit" type="submit">Search</button>
</form>

<a href="{% url 'phonebook:person_new' %}">New person</a>

<ol>
    {% for person in object_list %}
    <li>
    {{ person.name }} {{ person.surname }}
    {% if person.phonenumbers.all.count < 1 %}
    {% if person.emails.all.count < 1 %}
    <a href="{% url 'phonebook:person_delete' person.id %}">[Delete]</a>
    {% endif %}
    {% endif %}
    <a href="{% url 'phonebook:person_edit' person.id %}">[Edit]</a>
    <p>
    <ul>
        Phone numbers:
        <a href="{% url 'phonebook:phone_number_new' person.id %}">[Add]</a>
        {% for phone_number in person.phonenumbers.all %}
        <li>{{ phone_number.phone_number }}</li>
        {% endfor %}
    </ul>
    </p>
    <ul>
        Email adresses:
        <a href="{% url 'phonebook:email_new' person_id=person.pk %}">[Add]</a>
        {% for email in person.emails.all %}
        <li>{{ email.email }}</li>
        {% endfor %}
    </ul>
    </li>

    {% endfor %}
</ol>

phonebook/templates/phonebook/phonenumber_form.html
<h1><a href="{% url 'phonebook:person_list' %}"> phonebook </a></h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type=hidden name="person_id" value="{{ a_id }}">
    <input type="submit" value="Submit"/>
</form>